num_episodes: 72000
num_rollout_threads: 1
max_episode_length: 256
buffer_capacity: 2048
upgrade_threshold: 0.9
save_interval: 100
update_threshold: 1024
steps_per_update: 128
updates_per_time: 4
batch_size: 1024
lr_pi: 0.01 # learning rate for the policy optimizer
lr_q: 0.01 # learning rate for the critic optimizer
tau: 0.01 # target update rate
gamma: 0.95 # discount factor
alpha: 0.1 # weight of the entrophy term